
package project;

import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {
    
    Connection con;
    Statement st;
    ResultSet rs;
    ResultSetMetaData rd;
    
    String url = "jdbc:mysql://localhost:3306/project";
    String user = "root";
    String pass = "";
    
    public static int theme = 0;
    public static int userId=-1;
    public static String userName= "";

    
    public void conn(){
        try {
            con = DriverManager.getConnection(url, user, pass);
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("select * from users");
            rd  = rs.getMetaData();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    
    public Login() {
        initComponents();
//        getContentPane().setBackground(new Color (44, 62, 80));
        conn();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UName = new javax.swing.JTextField();
        LogIn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        showHide = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial Nova Cond Light", 3, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Item.png"))); // NOI18N
        jLabel1.setText("Welcome To ItemVerse  ");

        jLabel2.setFont(new java.awt.Font("Arial Nova Cond", 0, 18)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Arial Nova Cond", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        UName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNameActionPerformed(evt);
            }
        });

        LogIn.setFont(new java.awt.Font("Arial Nova Cond", 0, 14)); // NOI18N
        LogIn.setText("Log In");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Nova Cond", 0, 14)); // NOI18N
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Nova Cond", 0, 14)); // NOI18N
        jLabel4.setText("You don't have account? Register now");

        showHide.setFont(new java.awt.Font("Arial Nova Cond", 0, 12)); // NOI18N
        showHide.setText("Show Password");
        showHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jMenu6.setMnemonic('T');
        jMenu6.setText("Themes");

        jMenuItem12.setText("Light");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Dark");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuItem14.setText("Colorful");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showHide, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showHide)
                .addGap(30, 30, 30)
                .addComponent(LogIn)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Signup myf = new Signup();
        myf.setVisible(true);
        myf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideActionPerformed
        if(evt.getSource() == showHide && showHide.isSelected()){
                    password.setEchoChar((char)0);
                    showHide.setText("Hide Password");
                }else{
                    password.setEchoChar('*');
                    showHide.setText("Show Password");
                }
    }//GEN-LAST:event_showHideActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
         if(evt.getSource()==LogIn){
                try {
                    String s = UName.getText();
                    String s1 = password.getText();
                    rs = st.executeQuery("select * from users where user_name='"+s+"' and pass='"+s1+"'");
                    if (rs.next()){
                        Login.userId=rs.getInt(1);
                        Login.userName=rs.getString(2);
                        Home myf = new Home();
                        myf.setVisible(true);
                        myf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        dispose();   
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Error Password or User ID "+ UName.getText());
                }catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                } 
            }
    }//GEN-LAST:event_LogInActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        theme = 1;
        getContentPane().setBackground(new Color(248,250,252));
        for(Component comp : getContentPane().getComponents()){
            if(comp instanceof JTextField || comp instanceof JButton){
                comp.setBackground(new Color(217, 234, 253));
                comp.setForeground(new Color(0,0,0));
            }

            if(comp instanceof JLabel || comp instanceof JCheckBox){
                comp.setForeground(new Color(0,0,0));
            }

            if(comp instanceof JScrollPane jScrollPane ){
                Component view = jScrollPane.getViewport().getView();
                if(view instanceof JTextArea textArea){
                    textArea.setBackground(new Color(217, 234, 253));
                    textArea.setForeground(new Color(0,0,0));
                }
                if(view instanceof JTable table){
                    table.setBackground(new Color(217, 234, 253));
                    table.setForeground(new Color(0,0,0));
                }

            }
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        theme = 2;
        getContentPane().setBackground(new Color(34,40,49));
        for(Component comp : getContentPane().getComponents()){
            if(comp instanceof JTextField || comp instanceof JButton){
                comp.setBackground(new Color(57, 62, 70));
                comp.setForeground(new Color(238, 238, 238));
            }

            if(comp instanceof JLabel || comp instanceof JCheckBox){
                comp.setForeground(new Color(238, 238, 238));
            }

            if(comp instanceof JScrollPane jScrollPane ){
                Component view = jScrollPane.getViewport().getView();
                if(view instanceof JTextArea textArea){
                    textArea.setBackground(new Color(57, 62, 70));
                    textArea.setForeground(new Color(238, 238, 238));
                }
                if(view instanceof JTable table){
                    table.setBackground(new Color(57, 62, 70));
                    table.setForeground(new Color(238, 238, 238));
                }
            }

        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        theme = 3;
        getContentPane().setBackground(new Color(163, 92, 122));
        for(Component comp : getContentPane().getComponents()){
            if(comp instanceof JTextField || comp instanceof JButton){
                comp.setBackground(new Color(200 , 144 , 167));
                comp.setForeground(new Color(33,33,33));
            }

            if(comp instanceof JLabel || comp instanceof JCheckBox){
                comp.setForeground(new Color(251 ,245 ,229));
            }

            if(comp instanceof JScrollPane jScrollPane ){
                Component view = jScrollPane.getViewport().getView();
                if(view instanceof JTextArea textArea){
                    textArea.setBackground(new Color(200 , 144 , 167));
                    textArea.setForeground(new Color(33,33,33));
                }
                if(view instanceof JTable table){
                    table.setBackground(new Color(200 , 144 , 167));
                    table.setForeground(new Color(33,33,33));
                }
            }
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogIn;
    private javax.swing.JTextField UName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showHide;
    // End of variables declaration//GEN-END:variables
}
